// Generated by FlutterFire CLI & filled from google-services.json
// Project: civildpr-5972c

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android; // fallback
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOTSTYg-eJvljCknuyEir5C8Hckjl78M',
    appId: '1:602206536180:android:ec0275987299d3ca6139a1',
    messagingSenderId: '602206536180',
    projectId: 'civildpr-5972c',
    storageBucket: 'civildpr-5972c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOTSTYg-eJvljCknuyEir5C8Hckjl78M',
    appId: '1:602206536180:ios:ec0275987299d3ca6139a1',
    messagingSenderId: '602206536180',
    projectId: 'civildpr-5972c',
    storageBucket: 'civildpr-5972c.firebasestorage.app',
    iosBundleId: 'com.example.civilDpr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOTSTYg-eJvljCknuyEir5C8Hckjl78M',
    appId: '1:602206536180:web:ec0275987299d3ca6139a1',
    messagingSenderId: '602206536180',
    projectId: 'civildpr-5972c',
    storageBucket: 'civildpr-5972c.firebasestorage.app',
  );
}